name: Node CI
on: [push, pull_request]
jobs:
  build-test:
    name: Build & Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x, 16.x]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - name: yarn, yarn build, yarn test
      run: |
        yarn
        yarn build
        yarn test:unit
      env:
        CI: true
    - name: Upload coverage
      if: ${{ matrix.node-version == '16.x' }}
      run: bash <(curl -s https://codecov.io/bash)
