name: Node CI
on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"
jobs:
  build-test:
    name: Build & Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x, 22.x]
    steps:
    - uses: actions/checkout@v5
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install Dependencies
      run: yarn --frozen-lockfile
    - name: Lint
      run: yarn lint
    - name: yarn build, yarn test
      run: yarn build
      env:
        CI: true
    #- name: Unit Test
    #  run: yarn test:unit
    - name: E2E
      run: yarn test:e2e --headless
    - name: Upload coverage
      if: ${{ matrix.node-version == '22.x' }}
      uses: codecov/codecov-action@v5
