name: Node CI
on: [push, pull_request]
jobs:
  build-test:
    name: Build & Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x, 18.x]
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install Dependencies
      run: yarn --frozen-lockfile
    - name: Lint
      run: yarn lint
    - name: yarn build, yarn test
      run: yarn build
      env:
        CI: true
    - name: Unit Test
      run: yarn test:unit
    - name: E2E
      run: yarn test:e2e
    - name: Upload coverage
      if: ${{ matrix.node-version == '16.x' }}
      run: bash <(curl -s https://codecov.io/bash)
